// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vespoli.Data;

namespace Vespoli.Data.Migrations
{
    [DbContext(typeof(VespoliContext))]
    partial class VespoliContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Vespoli.Domain.Rower", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created");

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<string>("Introduction");

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("PasswordSalt");

                    b.Property<string>("School");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.ToTable("Rowers");
                });

            modelBuilder.Entity("Vespoli.Domain.Workout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Distance");

                    b.Property<string>("Note");

                    b.Property<int>("RowerId");

                    b.Property<DateTime>("WorkoutDate");

                    b.Property<double>("WorkoutTime");

                    b.HasKey("Id");

                    b.HasIndex("RowerId");

                    b.ToTable("Workouts");
                });

            modelBuilder.Entity("Vespoli.Domain.Workout", b =>
                {
                    b.HasOne("Vespoli.Domain.Rower", "Rower")
                        .WithMany("Workouts")
                        .HasForeignKey("RowerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
